-- Create batch_locks table for preventing concurrent batch processing
CREATE TABLE IF NOT EXISTS batch_locks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lock_key TEXT UNIQUE NOT NULL,
    locked_at DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_batch_locks_lock_key ON batch_locks(lock_key);

-- Enable RLS
ALTER TABLE batch_locks ENABLE ROW LEVEL SECURITY;

-- Allow all operations (adjust as needed for your security requirements)
CREATE POLICY "Allow all operations on batch_locks" ON batch_locks
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);