-- ======================================================
-- Setup script for Search Pattern Discovery Engine
-- Run this in your Supabase SQL Editor
-- ======================================================

-- 1. Add search_not_found column to ses_base_url (if not exists)
ALTER TABLE ses_base_url
ADD COLUMN IF NOT EXISTS search_not_found BOOLEAN DEFAULT FALSE;

-- 2. Create search_patterns table
CREATE TABLE IF NOT EXISTS search_patterns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_url_id BIGINT NOT NULL REFERENCES ses_base_url(base_url_id) ON DELETE CASCADE,
    base_url TEXT NOT NULL,
    pattern TEXT,
    strategy_used TEXT,
    confidence NUMERIC DEFAULT 0,
    result_type TEXT DEFAULT 'unknown',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(base_url_id)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_search_patterns_base_url_id ON search_patterns(base_url_id);
CREATE INDEX IF NOT EXISTS idx_search_patterns_strategy ON search_patterns(strategy_used);
CREATE INDEX IF NOT EXISTS idx_ses_base_url_unprocessed ON ses_base_url(search_processed) WHERE search_processed = FALSE;

-- 3. Enable RLS on search_patterns
ALTER TABLE search_patterns ENABLE ROW LEVEL SECURITY;

-- Allow service role full access
CREATE POLICY IF NOT EXISTS "Service role full access on search_patterns"
    ON search_patterns
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Allow authenticated users to read
CREATE POLICY IF NOT EXISTS "Authenticated read on search_patterns"
    ON search_patterns
    FOR SELECT
    TO authenticated
    USING (true);
